# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
ctrl-enter = 'exec-and-forget /Applications/Alacritty.app/Contents/MacOS/alacritty'
ctrl-b = 'exec-and-forget /Applications/Zen\ Browser.app/Contents/MacOS/zen'

# i3 wraps focus by defaulx
ctrl-h = 'focus --boundaries-action wrap-around-the-workspace left'
ctrl-j = 'focus --boundaries-action wrap-around-the-workspace down'
ctrl-k = 'focus --boundaries-action wrap-around-the-workspace up'
ctrl-l = 'focus --boundaries-action wrap-around-the-workspace right'

ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

ctrl-z = 'split horizontal'
ctrl-x = 'split vertical'
ctrl-f = 'fullscreen'

ctrl-s = 'layout v_accordion' # 'layout stacking' in i3
ctrl-w = 'layout h_accordion' # 'layout tabbed' in i3
ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'

ctrl-shift-c = 'reload-config'

ctrl-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5
