# Change the default Omarchy look'n'feel

general {
    gaps_in = 4
    gaps_out = 4
    layout = dwindle
}

decoration {
    rounding = 12
}

dwindle {
    preserve_split = true
    force_split = 0   # 0 = respect preselect direction, not aspect ratio
}
