apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd 
spec:
  secretName: argocd-server-tls
  dnsNames:
  - lab.ashudev.in
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

