[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.86
blur = true

[window.padding]
x = 2
y = 2

[font]
size = 10.5

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[general]
live_config_reload = true
