live_config_reload = true

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.6
blur = true

[window.padding]
x = 2
y = 2

[font]
size = 8.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"
