global:
  security:
    allowInsecureImages: true
auth:
  rootUser: minioadmin 
  rootPassword: minioadmin 
image:
  repository: bitnamilegacy/minio
console:
  image:
    repository: bitnamilegacy/minio-object-browser
